Repository boostcampwm2023/web11-SSOCK, pull requests merged in 2023-12, with the labels that each got.

#185 [오승엽] 받침대 db적용
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/mockdata.json
  front/src/pages/Visit/SnowBallProvider.tsx
Labels: week-75%, week4, FE

#187 [오승엽] 메시지 30개일때 렌더링x 수정
  front/src/pages/Visit/SnowBallProvider.tsx
  front/src/utils/position.tsx
  front/vite.config.ts
Labels: fixed, FE

#188 [김찬우] 로컬호스트 https 리퀘스트 오류 수정
  front/package-lock.json
  front/package.json
  front/vite.config.ts
Labels: fixed, week4, FE

#189 [송현우] clova api 연동
  back/src/common/interface/request.interface.ts
  back/src/common/strategy/google-auth.strategy.ts
  back/src/common/strategy/kakao-auth.strategy.ts
  back/src/common/strategy/naver-auth.strategy.ts
  back/src/modules/auth/auth.service.ts
  back/src/modules/message/dto/clova-content.dto.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.module.ts
  back/src/modules/message/message.service.ts
  back/src/modules/message/summary.service.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.service.ts
  back/src/modules/user/dto/user.dto.ts
  back/src/modules/user/entity/user.entity.ts
  back/src/modules/user/user.controller.ts
  back/src/modules/user/user.service.ts
  package-lock.json
  package.json
Labels: merge ready, BE

#195 [최진수] : 로그아웃 api +
  back/src/modules/auth/auth.controller.ts
Labels: merge ready, BE, week5

#194 [오승엽] visit페이지 스노우볼 이동 구현, 메시지 작성 api 예외처리, 새로운 메시지 표시, 메인장식 추가
  front/public/models/bcduck.glb
  front/public/models/bcduck_glasses.glb
  front/public/models/ground1.glb
  front/public/models/new.glb
  front/public/models/santa.glb
  front/public/models/tux.glb
  front/src/App.tsx
  front/src/components/Msg/Msg.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/components/SnowGlobeCanvas/models/Deco.tsx
  front/src/components/SnowGlobeCanvas/models/Glass.tsx
  front/src/components/SnowGlobeCanvas/models/Ground.tsx
  front/src/components/SnowGlobeCanvas/models/MainDeco.tsx
  front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
  front/src/components/SnowGlobeCanvas/models/Snow.tsx
  front/src/constants/deco.tsx
  front/src/mockdata.json
  front/src/pages/Make/Snowball/MainDeco/MakeSnowballCanvas.tsx
  front/src/pages/Visit/Deco/Deco.tsx
  front/src/pages/Visit/Deco/MsgBox.tsx
  front/src/pages/Visit/Deco/PostButton.tsx
  front/src/pages/Visit/Deco/Steps.tsx
  front/src/pages/Visit/SnowBallProvider.tsx
  front/src/pages/Visit/Visit.tsx
  front/src/pages/Visit/VisitBody.tsx
  front/src/pages/Visit/VisitHeader.tsx
  front/src/router/IsLogin.tsx
  front/src/utils/position.tsx
  front/src/utils/styled.tsx
Labels: week-100%, week4, FE

#199 [오승엽] 핫픽스!!!! 메시지작성 api url수정
  front/src/pages/Visit/Deco/PostButton.tsx
Labels: week-25%, fixed, FE, week5

#200 [오승엽] 진짜 핫픽스!!! 메시지 api변동 진짜 고침
  front/src/pages/Visit/Deco/PostButton.tsx
Labels: fixed, bug, FE

#198 [송현우] DML에 트랜잭션 적용
  back/src/common/interceptors/transaction.interceptor.ts
  back/src/common/interface/request.interface.ts
  back/src/modules/auth/auth.controller.ts
  back/src/modules/auth/auth.service.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.module.ts
  back/src/modules/message/message.service.ts
  back/src/modules/snowball/snowball.service.ts
  back/src/modules/user/user.controller.ts
  back/src/modules/user/user.service.ts
Labels: review, BE

#201 [송현우] pr 테스트
  back/src/modules/message/message.service.ts
Labels: bug, BE

#207 [서민아] 코드정리 및 사소한 버그 픽스
  front/public/models/img/Main/bcduck.gif
  front/public/models/img/Main/bcduck.png
  front/public/models/img/Main/bcduck_glasses.gif
  front/public/models/img/Main/santa.gif
  front/public/models/img/Main/snowman.gif
  front/public/models/img/Main/tree.gif
  front/public/models/img/Main/tree.png
  front/public/models/star.glb
  front/public/models/water.glb
  front/src/App.tsx
  front/src/components/Msg/ListMsg.tsx
  front/src/components/Msg/Msg.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/components/SnowGlobeCanvas/models/Emoji.tsx
  front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
  front/src/constants/deco.tsx
  front/src/pages/Main/ListMsgs.tsx
  front/src/pages/Main/MainButtonBox.tsx
  front/src/pages/Main/MenuModal.tsx
  front/src/pages/Make/Snowball/MainDeco/DecoBox.tsx
  front/src/pages/Make/Snowball/MainDeco/Steps.tsx
  front/src/pages/Visit/SnowBallProvider.tsx
  front/src/pages/Visit/Visit.tsx
  front/src/router/HasSnowballData.tsx
  front/src/router/index.tsx
Labels: week-25%, fixed, bug, FE, week5

#203 [최진수] : 서버 로거 구현
  back/src/app.module.ts
  back/src/common/interceptors/log.interceptor.ts
  back/src/main.ts
Labels: merge ready, BE, week5

#215 [송현우] update location api 완성
  back/src/common/interceptors/sample.intercepotr.ts
  back/src/modules/message/dto/update-message-location.dto.ts
  back/src/modules/message/dto/update-message-locations.dto.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.module.ts
  back/src/modules/message/message.service.ts
Labels: merge ready, BE

#227 [오승엽] 수많은 버그 수정
  front/public/icons/lock.svg
  front/public/icons/screen.svg
  front/public/icons/shareLink.svg
  front/public/icons/unlock.svg
  front/src/components/Modal/Modal.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/mockdata.json
  front/src/pages/Main/Main.tsx
  front/src/pages/Main/MainButtonBox.tsx
  front/src/pages/Visit/Deco/Deco.tsx
  front/src/pages/Visit/Deco/DecoEnroll.tsx
  front/src/pages/Visit/Deco/DecoProvider.tsx
  front/src/pages/Visit/SnowBallProvider.tsx
  front/src/pages/Visit/VisitBody.tsx
Labels: enhancement, week-50%, fixed, bug, FE, week6

#230 [김찬우] 비공개 공개 요청 모달 및 토스트 메세지 추가
  front/src/pages/Main/ListMsgs.tsx
  front/src/pages/Main/LockModal.tsx
  front/src/pages/Main/MainButtonBox.tsx
  front/src/pages/Visit/SnowBallProvider.tsx
Labels: week-50%, FE, week6

#231 [오승엽] 전체화면버튼 기능 수정
  front/src/components/Prev/Prev.tsx
  front/src/pages/Main/MainButtonBox.tsx
Labels: enhancement, week-100%, week6

#238 [오승엽] visit페이지에 홈으로 가는 버튼 추가
  front/src/pages/Visit/VisitHeader.tsx
Labels: enhancement, week-100%, FE, week6

#239 [김찬우] 라우터 분리
  front/src/App.tsx
  front/src/pages/Main/Main.tsx
  front/src/router/HasSnowballData.tsx
Labels: enhancement, FE

#241 [오승엽] 핫픽스! 전체화면 취소시 <>버튼 안생김
  front/src/pages/Main/MainButtonBox.tsx
Labels: fixed, bug
