Repository boostcampwm2023/web11-SSOCK, pull requests merged in 2023-11, with the labels that each got.

#4 [서민아] 프로토타입 설계
  front/.prettierrc
  front/package-lock.json
  front/package.json
  front/public/index.html
  front/src/App.css
  front/src/App.test.tsx
  front/src/App.tsx
  front/src/Cube.tsx
  front/src/Tree.tsx
  front/src/index.css
  front/src/index.tsx
  front/src/logo.svg
  front/src/react-app-env.d.ts
  front/src/reportWebVitals.ts
  front/src/setupTests.ts
Labels: week-1-FE-25%, merge ready

#7 [송현우] NestJS 초기 세팅
  back/.eslintrc.js
  back/.gitignore
  back/.prettierrc
  back/nest-cli.json
  back/package-lock.json
  back/package.json
  back/src/app.controller.spec.ts
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/app.service.ts
  back/src/main.ts
  back/src/modules/auth/auth.controller.ts
  back/src/modules/auth/auth.module.ts
  back/src/modules/auth/google-auth.service.ts
  back/test/app.e2e-spec.ts
  back/test/jest-e2e.json
  back/tsconfig.build.json
  back/tsconfig.json
Labels: merge ready

#10 [김찬우] 테스트 원기둥 추가 및 클릭 이벤트
  front/src/App.tsx
  front/src/Cube.tsx
  front/src/Cylinder.tsx
  front/src/Tree.tsx
Labels: week-25%, week1, FE

#9 [서민아] 버튼 제작, reset style 적용, utils 색상 정의
  front/package-lock.json
  front/package.json
  front/src/App.css
  front/src/App.tsx
  front/src/GlobalStyles.tsx
  front/src/components/Button/Button.tsx
  front/src/components/Button/index.tsx
  front/src/components/index.tsx
  front/src/utils/theme.tsx
  front/src/utils/utils.tsx
Labels: week-25%, merge ready, week1, FE

#13 [김찬우, 서민아, 오승엽] interface 내부 정의, colors 변수명 변경
  front/src/App.tsx
  front/src/GlobalStyles.tsx
  front/src/components/Button/Button.tsx
  front/src/utils/theme.tsx
  front/src/utils/utils.tsx
Labels: enhancement, FE

#11 [송현우] Oauth2.0 AuthStrategy 설계
  back/package-lock.json
  back/package.json
  back/src/modules/auth/auth.controller.ts
  back/src/modules/auth/auth.module.ts
  back/src/modules/auth/google-auth.strategy.ts
  back/src/modules/auth/kakao-auth.strategy.ts
  back/src/modules/auth/naver-auth.strategy.ts
Labels: review, in progress, BE

#25 [송현우] swagger api 작성 (auth/message/share 모듈)
  back/package-lock.json
  back/package.json
  back/src/app.controller.spec.ts
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/app.service.ts
  back/src/dtoTest.ts
  back/src/modules/auth/auth.controller.ts
  back/src/modules/message/dto/create-message.dto.ts
  back/src/modules/message/dto/delete-message.dto.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.controller.spec.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.service.spec.ts
  back/src/modules/message/message.service.ts
  back/src/modules/share/dto/create-share.dto.ts
  back/src/modules/share/dto/restore-share.dto.ts
  back/src/modules/share/share.controller.spec.ts
  back/src/modules/share/share.controller.ts
  back/src/modules/share/share.service.spec.ts
  back/src/modules/share/share.service.ts
  back/src/modules/snowball/snowball.controller.spec.ts
  back/src/modules/snowball/snowball.service.spec.ts
  back/src/util/swagger.ts
Labels: merge ready, BE

#26 [서민아] 소개페이지, 로그인 UI 및 애니메이션
  .gitignore
  front/index.html
  front/public/socialLogin/google.svg
  front/public/socialLogin/kakao.svg
  front/public/socialLogin/naver.svg
  front/src/App.tsx
  front/src/GlobalStyles.tsx
  front/src/components/Button/Button.tsx
  front/src/components/IntroButtonBox/IntroButtonBox.tsx
  front/src/components/IntroButtonBox/index.tsx
  front/src/components/Introduce/Introduce.tsx
  front/src/components/Introduce/index.tsx
  front/src/components/LoginBox/LoginBox.tsx
  front/src/components/LoginBox/index.tsx
  front/src/components/index.tsx
  front/src/utils/theme.tsx
Labels: week-75%, week1, FE

#27 [송현우] typeORM 설정
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/config/ormconfig.ts
  back/src/main.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.module.ts
  back/src/modules/message/message.service.ts
  back/tsconfig.json
Labels: fixed, merge ready, BE

#61 [오승엽] useFrame 속도 다른문제 해결
  front/src/components/SnowGlobeCanvas/Snow.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
Labels: review, week-50%, fixed, bug, week2, FE

#63 [최진수, 송현우] swagger api 작성 (message 모듈)
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/modules/message/dto/create-message.dto.ts
  back/src/modules/message/dto/delete-message.dto.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.service.ts
  back/src/modules/share/dto/create-share.dto.ts
  back/src/modules/share/dto/restore-share.dto.ts
  back/src/modules/share/share.controller.ts
  back/src/modules/share/share.module.ts
  back/src/modules/share/share.service.ts
  back/src/modules/snowball/dto/create-snowball.dto.ts
  back/src/modules/snowball/dto/decoration-snowball.dto.ts
  back/src/modules/snowball/dto/update-snowball.dto.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.module.ts
  back/src/modules/snowball/snowball.service.ts
  package-lock.json
Labels: bug, merge ready, BE

#64 [송현우] typeorm <-> mysql 연동
  back/package-lock.json
  back/package.json
  back/src/modules/message/dto/create-message.dto.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.service.ts
  back/src/modules/snowball/entity/snowball-decoration.entity.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/entity/user.entity.ts
  back/src/modules/snowball/snowball.controller.ts
Labels: fixed, merge ready, BE

#66 [송현우] erd 변경사항 적용
  back/package-lock.json
  back/package.json
  back/src/modules/auth/auth.controller.ts
  back/src/modules/message/dto/create-message.dto.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/snowball/dto/decoration-snowball.dto.ts
  back/src/modules/snowball/entity/snowball-decoration.entity.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/entity/user.entity.ts
  package-lock.json
Labels: merge ready, BE

#68 [최진수] 스노우볼 response DTO 생성
  .DS_Store
  back/src/modules/snowball/dto/req-create-snowball.dto.ts
  back/src/modules/snowball/dto/req-update-snowball.dto.ts
  back/src/modules/snowball/dto/res-create-snowball.dto.ts
  back/src/modules/snowball/dto/res-update-snowball.dto.ts
  back/src/modules/snowball/entity/user.entity.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.service.ts
Labels: in progress, merge ready, week2, BE

#96 [최진수] : 스노우볼 서비스 로직 구현
  back/.DS_Store
  back/src/modules/auth/auth.service.ts
  back/src/modules/snowball/dto/request/req-create-snowball.dto.ts
  back/src/modules/snowball/dto/request/req-update-snowball.dto.ts
  back/src/modules/snowball/dto/response/res-create-snowball.dto.ts
  back/src/modules/snowball/dto/response/res-update-decoration.dto.ts
  back/src/modules/snowball/dto/response/res-update-snowball.dto.ts
  back/src/modules/snowball/dto/snowball.dto.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.module.ts
  back/src/modules/snowball/snowball.service.ts
Labels: in progress, week3, BE

#98 [최진수] : 스노우볼 메시지 불러오는 요청 고침
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/snowball/entity/snowball-decoration.entity.ts
  back/src/modules/snowball/entity/snowball.entity.ts
Labels: fixed, merge ready, week3, BE

#101 [최진수] : CI/CD 구성중
  back/.dockerfile
  back/Dockerfile
Labels: week3, BE

#103 [오승엽] 장식 클릭시 메시지 컴포넌트 출력
  front/src/components/Msg/Msg.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/components/SnowGlobeCanvas/models/Deco.tsx
  front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
  front/src/constants/deco.tsx
  front/src/pages/Visit/MessageProvider.tsx
  front/src/pages/Visit/Visit.tsx
  front/src/pages/Visit/VisitButton.tsx
Labels: review, week-50%, week3, FE

#106 [송현우] swagger 인증 구현
  .github/workflows/FrontEnd.yml
  back/package-lock.json
  back/package.json
  back/src/main.ts
  back/src/util/swagger.ts
  back/tsconfig.json
Labels: merge ready

#107 [서민아] 배경음악 반복재생, 스노우볼 줌 나가기 버튼
  front/public/models/ribbonBox.glb
  front/src/GlobalStyles.tsx
  front/src/components/Button/PostButton.tsx
  front/src/components/Button/StepButton.tsx
  front/src/components/Button/index.tsx
  front/src/components/Msg/Msg.tsx
  front/src/components/Prev/Prev.tsx
  front/src/components/SnowGlobeCanvas/PrevProvider.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
  front/src/components/Song/Song.tsx
  front/src/constants/deco.tsx
  front/src/pages/Visit/Deco/Deco.tsx
  front/src/pages/Visit/Deco/DecoEnroll.tsx
  front/src/pages/Visit/Deco/Steps.tsx
Labels: week-50%, bug, week3, FE

#115 [서민아] UIContainer 적용
  front/src/components/Prev/Prev.tsx
  front/src/components/Song/Song.tsx
  front/src/pages/Main/ListMsg.tsx
  front/src/pages/Main/Main.tsx
  front/src/pages/Main/MainButtonBox.tsx
  front/src/pages/Main/MenuModal.tsx
  front/src/pages/Visit/Deco/Steps.tsx
Labels: week-50%, week3, FE

#118 [최진수] : 멘토님 리뷰반영해서 API 수정
  back/src/modules/auth/entity/user.entity.ts
  back/src/modules/message/dto/request/req-delete-message.dto.ts
  back/src/modules/message/entity/letter.entity.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.service.ts
  back/src/modules/snowball/entity/decoration-prefix.entity.ts
  back/src/modules/snowball/entity/snowball-decoration.entity.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.service.ts
Labels: in progress, week3, BE

#122 [서민아] 장식 선택
  front/public/modelsPng/Deco/fishBread.png
  front/public/modelsPng/Deco/gingerBread.png
  front/public/modelsPng/Deco/ribbonBox.png
  front/src/constants/deco.tsx
  front/src/pages/Visit/Deco/Deco.tsx
  front/src/pages/Visit/Deco/DecoBox.tsx
  front/src/pages/Visit/Deco/Steps.tsx
Labels: week-75%, week3, FE

#128 [송현우] 쿼리 최적화 및 서비스 로직
  back/src/modules/auth/auth.guard.ts
  back/src/modules/auth/auth.service.ts
  back/src/modules/auth/dto/response/res-info.dto.ts
  back/src/modules/auth/strategy/google-auth.strategy.ts
  back/src/modules/auth/strategy/kakao-auth.strategy.ts
  back/src/modules/auth/strategy/naver-auth.strategy.ts
  back/src/modules/message/entity/letter.entity.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/snowball/entity/decoration-prefix.entity.ts
  back/src/modules/snowball/entity/snowball-decoration.entity.ts
  back/src/modules/snowball/snowball.service.ts
Labels: BE

#129 [송현우] 서비스 로직 완성
  back/src/modules/auth/auth.guard.ts
  back/src/modules/auth/auth.service.ts
  back/src/modules/auth/dto/user.dto.ts
  back/src/modules/auth/entity/user.entity.ts
  back/src/modules/auth/strategy/google-auth.strategy.ts
  back/src/modules/auth/strategy/kakao-auth.strategy.ts
  back/src/modules/auth/strategy/naver-auth.strategy.ts
  back/src/modules/message/entity/letter.entity.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/snowball/entity/decoration-prefix.entity.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/util/swagger.ts
Labels: merge ready, BE

#130 [송현우] createMessage API 디버깅
  back/src/modules/message/message.service.ts
Labels: fixed, BE

#133 [오승엽] safri에서 주소창때문에 ui가려지는 문제 해결
  front/src/App.tsx
  front/src/GlobalStyles.tsx
Labels: week-100%, bug, week3, FE

#157 [FE] 로그인 확인용 a 태그
  front/src/pages/Intro/Introduce.tsx
  front/src/pages/Intro/LoginBox.tsx
Labels: FE

#158 [FE] a태그 overflow 해결
  front/src/pages/Intro/Introduce.tsx
Labels: FE

#159 [오승엽] snow변경, 회전추가
  front/public/models/bottom2.glb
  front/public/models/snowFlake01.glb
  front/public/models/snowFlake02.glb
  front/public/models/snowFlake03.glb
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/components/SnowGlobeCanvas/models/Snow.tsx
  front/src/pages/Intro/Introduce.tsx
  front/src/pages/Intro/LoginBox.tsx
Labels: week-25%, week4, FE

#161 [송현우] 모듈 개선, user 모듈 작성, 닉네임 update 서비스 작성
  back/src/app.module.ts
  back/src/modules/auth/auth.controller.ts
  back/src/modules/auth/auth.guard.ts
  back/src/modules/auth/auth.module.ts
  back/src/modules/auth/auth.service.ts
  back/src/modules/auth/dto/response/res-info.dto.ts
  back/src/modules/auth/strategy/google-auth.strategy.ts
  back/src/modules/message/dto/request/req-create-message.dto.ts
  back/src/modules/message/dto/update-message-decoration.dto.ts
  back/src/modules/message/dto/update-message-location.dto.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/message/message.module.ts
  back/src/modules/message/message.service.ts
  back/src/modules/snowball/dto/request/req-create-snowball.dto.ts
  back/src/modules/snowball/dto/update-main-decoration.dto.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/snowball.module.ts
  back/src/modules/snowball/snowball.service.ts
  back/src/modules/user/dto/nickname.dto.ts
  back/src/modules/user/dto/response/res-info.dto.ts
  back/src/modules/user/dto/user.dto.ts
  back/src/modules/user/entity/user.entity.ts
  back/src/modules/user/user.controller.ts
  back/src/modules/user/user.module.ts
  back/src/modules/user/user.service.ts
  back/test/app.e2e-spec.ts
  back/test/jest-e2e.json
Labels: review, BE

#162 [송현우] access token 저장, todo 메모
  back/src/modules/auth/auth.controller.ts
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/user/entity/user.entity.ts
Labels: merge ready, BE

#166 [김찬우] snowball 생성 UI 로직 구현
  front/src/App.tsx
  front/src/GlobalStyles.tsx
  front/src/components/Button/MakeButton.tsx
  front/src/components/Button/index.tsx
  front/src/components/Input/InputSnowball.tsx
  front/src/components/Input/index.tsx
  front/src/components/SnowGlobeCanvas/models/Snow.tsx
  front/src/components/index.tsx
  front/src/pages/MainDeco/DecoBox.tsx
  front/src/pages/MainDeco/DecoEnroll.tsx
  front/src/pages/MainDeco/DecoProvider.tsx
  front/src/pages/MainDeco/MainDeco.tsx
  front/src/pages/MainDeco/MsgBox.tsx
  front/src/pages/MainDeco/SnowballNameProvider.tsx
  front/src/pages/MainDeco/Steps.tsx
  front/src/pages/MainDeco/index.tsx
  front/src/pages/index.tsx
Labels: review, week-25%, week4, FE

#168 [송현우] 스노우볼 생성 및 조회 프론트 연동
  back/src/modules/message/entity/message.entity.ts
  back/src/modules/message/message.service.ts
  back/src/modules/snowball/entity/snowball.entity.ts
  back/src/modules/snowball/snowball.controller.ts
Labels: BE

#175 [최진수] : 스노우볼 서비스 로직 변경. 벨리데이션 추가
  back/src/common/guards/hasJwt.guard.ts
  back/src/common/interceptors/jwtRequest.interceptor.ts
  back/src/common/interface/request.interface.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.module.ts
  back/src/modules/snowball/snowball.service.ts
Labels: in progress, BE

#173 [김찬우] 프로젝트들 소개 페이지 생성
  front/public/img/tempThumbnail.png
  front/src/App.tsx
  front/src/pages/Boostcamp/Boostcamp.tsx
  front/src/pages/Boostcamp/index.tsx
  front/src/pages/index.tsx
Labels: week-50%, week4, FE

#177 [김찬우] router 예외처리 구현
  front/src/App.tsx
  front/src/router/HasSnowball.tsx
  front/src/router/IsLogin.tsx
  front/src/router/index.tsx
Labels: review, week-50%, week4, FE

#179 [송현우] 요청 헤더 authorization -> cookie로 변환
  back/src/common/guards/jwt.guard.ts
  back/src/common/interceptors/hasJwt.interceptor.ts
  back/src/common/util/swagger.ts
  back/src/modules/auth/auth.controller.ts
  back/src/modules/message/message.controller.ts
  back/src/modules/snowball/snowball.controller.ts
  back/src/modules/snowball/snowball.module.ts
  back/src/modules/snowball/snowball.service.ts
  back/src/modules/user/user.controller.ts
Labels: merge ready, BE

#181 [FE] router test
  front/src/App.tsx
  front/src/router/IsLogin.tsx
Labels: FE
