Repository boostcampwm2023/web11-SSOCK, pull requests merged in 2024-01, with the labels that each got.

#246 [김찬우] Main 페이지 컴포넌트 구조 리팩토링
  front/src/pages/Intro/Introduce.tsx
  front/src/pages/Main/LockModal.tsx
  front/src/pages/Main/Main.tsx
  front/src/pages/Main/MainBody.tsx
  front/src/pages/Main/MainButtonBox.tsx
  front/src/pages/Main/MainFooter.tsx
  front/src/pages/Main/MainHeader.tsx
Labels: enhancement, review, refactor, in progress, FE

#247 [김찬우] 볼멍 애니메이션 효과 리팩토링
  front/src/pages/Main/Main.tsx
  front/src/pages/Main/MainBody.tsx
  front/src/pages/Main/MainFooter.tsx
  front/src/pages/Main/MainHeader.tsx
Labels: enhancement, refactor, fixed, FE

#248 [김찬우] 코드스플리팅 적용
  front/src/App.tsx
Labels: enhancement, refactor, FE

#249 [김찬우] 메타 태그, img alt 속성 추가 및 청크 크기 분리
  front/index.html
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/components/SnowGlobeCanvas/Decos.tsx
  front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
  front/src/components/SnowGlobeCanvas/models/Bottom.tsx
  front/src/components/SnowGlobeCanvas/models/Deco.tsx
  front/src/components/SnowGlobeCanvas/models/Emoji.tsx
  front/src/components/SnowGlobeCanvas/models/Glass.tsx
  front/src/components/SnowGlobeCanvas/models/Ground.tsx
  front/src/components/SnowGlobeCanvas/models/MainDeco.tsx
  front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
  front/src/components/SnowGlobeCanvas/models/Snow.tsx
  front/src/components/Song/Song.tsx
  front/src/index.tsx
  front/src/pages/Make/Snowball/MainDeco/MakeSnowballCanvas.tsx
  front/src/pages/Visit/Deco/DecoCanvas/DecoCanvas.tsx
  front/src/pages/Visit/Deco/DecoCanvas/DecoModel.tsx
  front/src/utils/axios.tsx
  front/src/utils/index.tsx
  front/src/utils/meshUtils.tsx
  front/src/utils/position.tsx
  front/vite.config.ts
Labels: enhancement, refactor, FE

#251 [서민아] MessageListProvider recoil 변환
  front/src/components/Modal/Modal.tsx
  front/src/components/SnowGlobeCanvas/Decos.tsx
  front/src/pages/Intro/Intro.tsx
  front/src/pages/Main/Main.tsx
  front/src/pages/Main/MainBody.tsx
  front/src/pages/Visit/MessageListProvider.tsx
  front/src/pages/Visit/Visit.tsx
  front/src/pages/Visit/VisitBody.tsx
  front/src/pages/Visit/VisitHeader.tsx
  front/src/router/Router.tsx
  front/src/states/atoms.tsx
  front/src/states/index.tsx
Labels: enhancement, refactor, FE

#257 [서민아] 메시지 작성 후 뒤로가기 버튼 오류 수정
  front/src/pages/Visit/Deco/DecoEnroll.tsx
Labels: fixed, bug, FE
